{
 "title": "swa_tnt",
 "description": "universal dashboard for all tarantools",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "graphite", "label": "graphite", "query": "graphite" },
   { "name": "type", "label": "type", "query": "swa.tnt.*" },
   { "name": "host", "label": "host", "query": "swa.tnt.$type.*" },
   { "name": "instance", "label": "instance", "query": "swa.tnt.$type.$host.*" },
   {
    "name": "file",
    "label": "file",
    "query": "swa.tnt.$type.$host.$instance.imagine.files.*"
   },
   {
    "name": "space",
    "query": "swa.tnt.$type.$host.$instance.imagine.space.*"
   }
  ]
 },
 "panels": [
  { "title": "common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "errors and warnings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "errors" }
   ],
   "targets": [
    {
     "target": "alias(groupByNode(removeBelowValue(swa.tnt.$type.$host.$instance.error_rps_max, 1), 5, 'sum'), 'errors')"
    }
   ]
  },
  {
   "title": "arena trend (highest max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(highestMax(swa.tnt.$type.$host.$instance.arena_used, 1), '.*_([^_]+).*', '\\1')"
    }
   ]
  },
  {
   "title": "memory (sum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 100), 'quota size')"
    },
    {
     "target": "alias(keepLastValue(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 100), 'quota used')"
    },
    {
     "target": "alias(keepLastValue(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 100), 'arena size')"
    },
    {
     "target": "alias(keepLastValue(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 100), 'arena used')"
    },
    {
     "target": "alias(keepLastValue(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 100), 'lua heap')"
    }
   ]
  },
  {
   "title": "a. size / q. size (max)",
   "type": "singlestat",
   "description": "когда arena_size доходит до quota_size возможны ошибки при добавлении новых данных (если не найдется свободного slab'а нужного размера)",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "highestCurrent(divideSeries(#B, #A), 1)",
     "targetFull": "highestCurrent(divideSeries(swa.tnt.$type.$host.$instance.arena_size, lowestCurrent(swa.tnt.$type.$host.$instance.quota_size, 1)), 1)"
    }
   ]
  },
  {
   "title": "a. used / q. size (sum)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(#B, #A)",
     "targetFull": "divideSeries(sumSeries(swa.tnt.$type.$host.$instance.arena_used), sumSeries(swa.tnt.$type.$host.$instance.quota_size))"
    }
   ]
  },
  {
   "title": "resources for",
   "type": "singlestat",
   "description": "оценка времени, на которое хватит ресурсов (пока arena_used не дойдет до quota_size), учитывая среднюю скорость роста арены за 2 последних дня",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 8 },
   "format": "d",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(scale(diffSeries(absolute(#E), #E),1),#E)",
     "targetFull": "sumSeries(scale(diffSeries(absolute(movingAverage(divideSeries(scale(sumSeries(swa.tnt.$type.$host.$instance.quota_size,scale(sumSeries(swa.tnt.$type.$host.$instance.arena_used),-1.05)),2),sumSeries(sumSeries(timeShift(swa.tnt.$type.$host.$instance.arena_used, '1h')),scale(sumSeries(timeShift(swa.tnt.$type.$host.$instance.arena_used, '2d')), -1))),100)), #E),1),#E)"
    }
   ]
  },
  {
   "title": "replication idle (max)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "refCount": -1,
     "target": "keepLastValue(maxSeries(swa.tnt.$type.$host.$instance.replication_idle), 10)"
    }
   ]
  },
  { "title": "files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$file",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4.8, "x": 0, "y": 11 },
   "repeat": "file",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "absolute(diffSeries(#B, #A))",
     "targetFull": "absolute(diffSeries(keepLastValue(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100), keepLastValue(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100)))"
    }
   ]
  },
  {
   "title": "$file",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4.8, "x": 4.8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "absolute(diffSeries(#B, #A))",
     "targetFull": "absolute(diffSeries(keepLastValue(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100), keepLastValue(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100)))"
    }
   ]
  },
  {
   "title": "$file",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4.8, "x": 9.6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "absolute(diffSeries(#B, #A))",
     "targetFull": "absolute(diffSeries(keepLastValue(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100), keepLastValue(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100)))"
    }
   ]
  },
  {
   "title": "$file",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4.8, "x": 14.399999999999999, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "absolute(diffSeries(#B, #A))",
     "targetFull": "absolute(diffSeries(keepLastValue(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100), keepLastValue(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100)))"
    }
   ]
  },
  {
   "title": "$file",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4.8, "x": 19.2, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "absolute(diffSeries(#B, #A))",
     "targetFull": "absolute(diffSeries(keepLastValue(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100), keepLastValue(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 100)))"
    }
   ]
  },
  {
   "title": "functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "target": "aliasSub(maximumAbove(groupByNode(consolidateBy(swa.tnt.$type.$host.$instance.imagine.funcs.*_rpm, 'max'), 7, 'sumSeries'), 0), '(.*)_rpm.*', '\\1')"
      }
     ]
    },
    {
     "title": "timings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasSub(maximumAbove(groupByNode(consolidateBy(exclude(swa.tnt.$type.$host.$instance.imagine.funcs.*, '.*_rpm.*'), 'max'), 7, 'maxSeries'), 0), '(.*),.*', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "basic operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "basic operations (max avg per min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "target": "aliasSub(consolidateBy(groupByNode(swa.tnt.$type.$host.$instance.*_rps_avg, 5, 'sum'), 'max'), '.*\\((.*)_rps_avg.*', '\\1')"
      }
     ]
    },
    {
     "title": "basic operations (max)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "target": "aliasSub(consolidateBy(groupByNode(swa.tnt.$type.$host.$instance.*_rps_max, 5, 'sum'), 'max'), '.*\\((.*)_rps_max.*', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "expirationd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(maximumAbove(aliasSub(groupByNode(consolidateBy(swa.tnt.$type.$host.$instance.imagine.expd.*_rpm, 'max'), 7, 'maxSeries'), '(.*)_rpm.*', '\\1'), 0))"
      }
     ]
    },
    {
     "title": "timings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "aliasSub(maximumAbove(groupByNode(consolidateBy(exclude(swa.tnt.$type.$host.$instance.imagine.expd.*, '.*_rpm.*'), 'max'), 7, 'maxSeries'), 0), '(.*),.*', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 }, "content": "\n#### by host\n\n\n\n" },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 }, "content": "\n#### by instance\n\n\n\n" },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "repeat": "instance",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_size, 0, 'sum'), 'quota size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.quota_used, 0, 'sum'), 'quota used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_size, 0, 'sum'), 'arena size')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.arena_used, 0, 'sum'), 'arena used')"
      },
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.mem.lua_interp_sz, 0, 'sum'), 'lua heap')"
      }
     ]
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 }, "content": "\n#### by host\n\n\n\n" },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "repeat": "host",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'sum'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'sum'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'sum'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'sum'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'sum'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'sum'), 'CPU usage')"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 }, "content": "\n#### by instance\n\n\n\n" },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "repeat": "instance",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias(groupByNode(swa.tnt.$type.$host.$instance.cpu_usage, 0, 'maxSeries'), 'CPU usage')"
      }
     ]
    }
   ]
  },
  {
   "title": "files history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 0, "y": 19 },
     "repeat": "file",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    },
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    },
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    },
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    },
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    },
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    },
    {
     "title": "$file.lua",
     "type": "graph",
     "gridPos": { "h": 7, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'max')"
      },
      {
       "target": "alias(minSeries(swa.tnt.$type.$host.$instance.imagine.files.$file), 'min')"
      }
     ]
    }
   ]
  },
  {
   "title": "fibers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "fibers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(maximumAbove(aliasByMetric(groupByNode(consolidateBy(swa.tnt.$type.$host.$instance.imagine.fiber.*, 'max'), 7, 'sumSeries')), 0), '(.*),.*', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "spaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "size of spaces (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "repeat": "space",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$space space size trend (sum)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.$space, 7, 'sum')"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 }, "content": "\n#### by host\n\n\n\n" },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 }, "content": "\n#### by instance\n\n\n\n" },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    },
    {
     "title": "$instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNode(swa.tnt.$type.$host.$instance.imagine.space.*, 7, 'sum')"
      }
     ]
    }
   ]
  }
 ]
}